### ISSUE TITLE
Please add a license and a screen shot

### ISSUE THREAD

**Issue by unixorn** [andreshincapier/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Finally, please consider renaming the repository to match the name of the theme file.

Thanks!

**Comment by andreshincapier** [comment]
Hi @unixorn, a screenshot has been added, as it also refers to the use of licenses, thank you very much for your comments, and help me improve the contributions in the wonderful world of open source.

**Comment by unixorn** [comment]
One last thing - can you rename it to something less generic than `zsh-theme`? even just naming it after your github username would be better.

**Comment by andreshincapier** [comment]
**@unixorn** Once again, thank you very much for your comments, I already gave it a name that I think looks great, greetings
